// <auto-generated />
namespace CodeFirst.Vitzy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AlterColumnNameMaxLength255AndNotNullToGenreTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterColumnNameMaxLength255AndNotNullToGenreTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202308100456324_AlterColumnNameMaxLength255AndNotNullToGenreTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
